/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Stammdatenverwaltung;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author dachs
 */
public class ProduktControllerUI extends javax.swing.JFrame {

    /**
     * Creates new form ProduktControllerUI
     */
    public ProduktControllerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listPanel = new javax.swing.JScrollPane();
        produktList = new javax.swing.JList<>();
        newButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        listButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        mainMenuBare = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMenu = new javax.swing.JMenu();
        newRezeptMenu = new javax.swing.JMenuItem();
        newProduktMenu = new javax.swing.JMenuItem();
        newZutatMenu = new javax.swing.JMenuItem();
        mainMenu = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        produktMenu = new javax.swing.JMenuItem();
        zutatenMenu = new javax.swing.JMenuItem();
        rezeptMenu = new javax.swing.JMenuItem();
        extrasMenu = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenuItem();
        infoMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        produktList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("produktController.getProduktliste()");
        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listPanel, eLProperty, produktList);
        bindingGroup.addBinding(jListBinding);

        listPanel.setViewportView(produktList);

        newButton.setText("New");

        editButton.setText("Edit");

        listButton.setText("List");

        deleteButton.setText("Delete");

        fileMenu.setText("File");

        newMenu.setText("New...");

        newRezeptMenu.setText("Rezept");
        newMenu.add(newRezeptMenu);

        newProduktMenu.setText("Produkt");
        newMenu.add(newProduktMenu);

        newZutatMenu.setText("Zutat");
        newMenu.add(newZutatMenu);

        fileMenu.add(newMenu);

        mainMenu.setText("Main");
        fileMenu.add(mainMenu);

        exitMenu.setText("Exit");
        fileMenu.add(exitMenu);

        mainMenuBare.add(fileMenu);

        editMenu.setText("Edit");

        produktMenu.setText("Produkte");
        produktMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produktMenuActionPerformed(evt);
            }
        });
        editMenu.add(produktMenu);

        zutatenMenu.setText("Zutaten");
        editMenu.add(zutatenMenu);

        rezeptMenu.setText("Rezepte");
        editMenu.add(rezeptMenu);

        mainMenuBare.add(editMenu);

        extrasMenu.setText("Extras");

        helpMenu.setText("Help");
        extrasMenu.add(helpMenu);

        infoMenu.setText("Info");
        extrasMenu.add(infoMenu);

        mainMenuBare.add(extrasMenu);

        setJMenuBar(mainMenuBare);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(listPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(newButton)
                .addGap(18, 18, 18)
                .addComponent(editButton)
                .addGap(28, 28, 28)
                .addComponent(listButton)
                .addGap(29, 29, 29)
                .addComponent(deleteButton)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton)
                    .addComponent(editButton)
                    .addComponent(listButton)
                    .addComponent(deleteButton))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void produktMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produktMenuActionPerformed
        // TODO add your handling code here:
        DefaultListModel listModel = new DefaultListModel();
        String produkt;
        ArrayList<Produkt> produktListe = ProduktController.getProduktliste();
        for (Produkt o : produktListe)  {
            produkt = o.getBezeichnung();
            listModel.addElement(produkt);
        }
        
        
    }//GEN-LAST:event_produktMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenu extrasMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem helpMenu;
    private javax.swing.JMenuItem infoMenu;
    private javax.swing.JButton listButton;
    private javax.swing.JScrollPane listPanel;
    private javax.swing.JMenuItem mainMenu;
    private javax.swing.JMenuBar mainMenuBare;
    private javax.swing.JButton newButton;
    private javax.swing.JMenu newMenu;
    private javax.swing.JMenuItem newProduktMenu;
    private javax.swing.JMenuItem newRezeptMenu;
    private javax.swing.JMenuItem newZutatMenu;
    private javax.swing.JList<String> produktList;
    private javax.swing.JMenuItem produktMenu;
    private javax.swing.JMenuItem rezeptMenu;
    private javax.swing.JMenuItem zutatenMenu;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
